services:
  backend:
    build: ./backend
    container_name: kimnguyen_backend
    image: kimnguyen_flask_backend
    volumes:
      - ./logs:/logs
    ports:
    - "5000:5000"
    environment:
      - LOG_PATH=/logs

  frontend:
    image: nginx:latest
    container_name: kimnguyen_frontend
    ports:
      - "8090:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
